### ISSUE TITLE
cannot load such file -- ant

### ISSUE THREAD

**Issue by 759803573** [iconara/rubydoop#31]
I clone this repository  and cd example/word_count/  
when I bundle install  && rake packags
 the error

rake aborted!
cannot load such file -- ant

(See full trace by running task with --trace)

**Comment by iconara** [comment]
Have you tried installing Ant?

**Comment by 759803573** [comment]
Yes,I install Ant
![2015-07-08 09 14 18](https://cloud.githubusercontent.com/assets/9429246/8561053/f83db00c-2551-11e5-8d6d-4dc20bd182d6.png)

Sorry, my English is not well

**Comment by wudixiaotie** [comment]
I had this problem too, and I install ant too.
![2015-07-17 15 48 13](https://cloud.githubusercontent.com/assets/3015256/8742773/47fc8064-2c9b-11e5-864b-183f2cc1b387.png)

**Comment by wudixiaotie** [comment]
I installed java and ruby, but not jruby, should I install jruby?

**Comment by iconara** [comment]
Yes, Rubydoop only runs in JRuby.

**Comment by wudixiaotie** [comment]
If I installed jruby, when I run "rake package", the rubydoop will automatic run jruby，not ruby?

**Comment by iconara** [comment]
Probably, but it depends on how you install things. If `ruby -v` says it's JRuby then `rake package` will most likely also run in JRuby. I can't help you get JRuby correctly installed.

**Comment by wudixiaotie** [comment]
Ok I know, that's simple, I just need to set some of my work folder use jruby as default. It is easy when I have rvm.Thank you very much. Have a nice day。 :+1: :+1: :+1:

**Comment by 759803573** [comment]
thank you
